version: "3.9"
services:
  spark-master:
    container_name: "spark-master"
    image: bitnami/spark:latest
    depends_on:
      - hadoop
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_URL=spark://spark-master:7077
    volumes:
      - "./infrastructure/spark/spark-defaults.conf:/opt/bitnami/spark/conf/spark-defaults.conf"
    ports:
      - "7077:7077"
  hadoop:
    container_name: "hadoop"
    build:
      context: infrastructure
      dockerfile: infrastructure/Dockerfile.hadoop
    environment:
      - USER=hadoop
    ports:
      - "8021:8021"
      - "9000:9000"
      - "2222:22"
      - "50070:50070"
  postgres:
    container_name: "postgres"
    image: postgres:14.0-alpine
    volumes:
      - "./infrastructure/postgres:docker-entrypoint-initdb.d"
    environment:
      POSTGRES_DB: "event"
      POSTGRES_USER: "event"
      POSTGRES_PASSWORD: "event"
    ports:
      - "5432:5432"
  debezium:
    container_name: "debezium"
    image: debezium/connect:latest
    depends_on:
      - postgres
    volumes:
      - "./infrastructure/debezium:/scripts"
    environment:
      - BOOTSTRAP_SERVERS=localhost:9092
      - GROUP_ID=debezium
      - CONFIG_STORAGE_TOPIC=debezium-configs
      - OFFSET_STORAGE_TOPIC=debezium-offset
      - STATUS_STORAGE_TOPIC=debezium-status
      - KEY_CONVERTER=org.apache.kafka.connect.storage.StringConverter
      - VALUE_CONVERTER=org.apache.kafka.connect.storage.StringConverter
  spark-edu:
    container_name: "spark-edu"
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - hadoop
      - spark-master
    environment:
      - "POSTGRES_URL=postgres:5432"
      - "HDFS_URL=hadoop:9000"
      - "DEBEZIUM_URL=debezium:8083"
    ports:
      - "8080:8080"