app:
  filePath: hdfs://${HDFS_URL:localhost:9000}/data/*.csv
  startType: "READ_KAFKA"
  kafka-topics:
    - "event"
  kafka-servers:
    - "localhost:9092"
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_URL:localhost:5433}/postgres
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:91823God}
  liquibase:
    change-log: db/changelog/master.yml
    user:  ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:91823God}
    url: jdbc:postgresql://${POSTGRES_URL:localhost:5433}/postgres

logging:
  level:
    root: info