#  https://postgreshelp.com/how-to-setup-greenplum-database/
version: "3.9"
services:
  hadoop:
    container_name: "hadoop"
    restart: on-failure
    build:
      context: hadoop
      dockerfile: hadoop/Dockerfile.hadoop
    environment:
      - USER=hadoop
    ports:
      - "8021:8021"
      - "9000:9000"
      - "2222:22"
      - "50070:50070"
  greenplum-master:
    container_name: greenplum-master
    restart: on-failure
    depends_on:
      - hadoop
    build:
      context: gp
      dockerfile: Dockerfile
    entrypoint: [ "/bin/sh", "-c", "/home/greenplum/start-master.sh" ]
    volumes:
      - "./gp/master/1:/home/greenplum//data/master"
      - "./gp/data/primary/1:/home/greenplum/data/primary"
      - "./gp/data/mirror/1:/home/greenplum/data/mirror"
    environment:
      MASTER_DATA_DIRECTORY: "/home/greenplum/data/master"
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
      - "88:22"
  greenplum-primary1:
    container_name: greenplum-primary1
    restart: on-failure
    depends_on:
      - hadoop
      - greenplum-master
    build:
      context: gp
      dockerfile: Dockerfile
    entrypoint: [ "/bin/sh", "-c", "sleep infinity" ]
    volumes:
      - "./gp/master/2:/home/greenplum//data/master"
      - "./gp/data/primary/2:/home/greenplum/data/primary"
      - "./gp/data/mirror/2:/home/greenplum/data/mirror"
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"