#  https://postgreshelp.com/how-to-setup-greenplum-database/
version: "3.9"
services:
  hadoop:
    container_name: "hadoop"
    restart: on-failure
    networks:
      - gp_network
    build:
      context: hadoop
      dockerfile: hadoop/Dockerfile.hadoop
    environment:
      - USER=hadoop
    ports:
      - "8021:8021"
      - "9000:9000"
      - "2222:22"
      - "50070:50070"
  greenplum-master:
    container_name: mdw
    restart: on-failure
    networks:
      - gp_network
    depends_on:
      - hadoop
      - greenplum-primary1
    cap_add:
      - NET_ADMIN
    build:
      context: gp
      dockerfile: Dockerfile
    user: "1280:1280"
    stdin_open: true
    entrypoint:
      - "/bin/sh"
      - "-c"
      - "./sbin/start-master.sh"
    volumes:
      - "./gp/master:/home/gpadmin/data/master"
    environment:
      LOG_DIRECTORY: "./log"
      MASTER_DATA_DIRECTORY: "./data/master"
      PGDATABASE: "postgres"
      PGUSER: "postgres"
      PGPASSWORD: "postgres"
    ports:
      - "5432:5432"
      - "88:22"
  greenplum-primary1:
    container_name: sdw1
    restart: on-failure
    networks:
      - gp_network
    depends_on:
      - hadoop
    cap_add:
      - NET_ADMIN
    build:
      context: gp
      dockerfile: Dockerfile
    user: "1280:1280"
    stdin_open: true
    entrypoint:
      - "/bin/sh"
      - "-c"
      - "./sbin/start-primary.sh"
    volumes:
      - "./gp/data/primary/2:/home/gpadmin/data/primary"
      - "./gp/data/mirror/2:/home/gpadmin/data/mirror"
    environment:
      LOG_DIRECTORY: "./log"
      MASTER_DATA_DIRECTORY: "./data/master"
    ports:
      - "22:22"

networks:
  gp_network:
    driver: bridge